events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend:5000;
        }

        location /add {
            proxy_pass http://addition:5000;
        }

        location /multiply {
            proxy_pass http://multiplication:5000;
        }
    }
}