- name: Deploy Microservices App
  hosts: localhost
  become: false

  tasks:

    - name: Remove old project
      file:
        path: /tmp/microservices
        state: absent

    - name: Copy project files
      copy:
        src: ../
        dest: /tmp/microservices

    - name: Run Docker Compose
      command: docker-compose up --build -d
      args:
        chdir: /tmp/microservices